FROM node:8.15.1-alpine

RUN apk add --no-cache curl

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

# Copy both package.json and package-lock.json
COPY package*.json ./

USER node

# Use npm install instead of npm ci
RUN npm install --only=production

# Copy other project files and set correct permissions
COPY --chown=node:node . .

EXPOSE 3000

CMD ["npm", "run", "start"]